/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.DuAn1.volleyballshoes.app.ui.main;

import com.DuAn1.volleyballshoes.app.ui.StaffManagement;

/**
 *
 * @author nickh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        initComponents();
        getContentPane().removeAll();
        getContentPane().setLayout(new java.awt.BorderLayout());
        sidebar1.setPreferredSize(new java.awt.Dimension(180, 600));
        sidebar1.setMinimumSize(new java.awt.Dimension(180, 400));
        sidebar1.setMaximumSize(new java.awt.Dimension(180, Integer.MAX_VALUE));
        getContentPane().add(sidebar1, java.awt.BorderLayout.WEST);
        jPanel2.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
        sidebar1.addSidebarItem("Trang chủ", "/com/DuAn1/volleyballshoes/app/icons/home.png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("home");
            }
        });
        sidebar1.addSidebarItem("Bán hàng", "/com/DuAn1/volleyballshoes/app/icons/shopping-cart.png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("sell");
            }
        });
        sidebar1.addSidebarItem("Sản phẩm", "/com/DuAn1/volleyballshoes/app/icons/box-open.png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("product");
            }
        });
        sidebar1.addSidebarItem("Nhân viên", "/com/DuAn1/volleyballshoes/app/icons/user.png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("staff");
            }
        });
        sidebar1.addSidebarItem("Khuyến mãi", "/com/DuAn1/volleyballshoes/app/icons/ticket.png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("promotion");
            }
        });
        sidebar1.addSidebarItem("Hóa đơn", "/com/DuAn1/volleyballshoes/app/icons/file-invoice-dollar.png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("invoice");
            }
        });
        sidebar1.addSidebarItem("Khách hàng", "/com/DuAn1/volleyballshoes/app/icons/users (8).png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("customer");
            }
        });
        sidebar1.addSidebarItem("Thống kê", "/com/DuAn1/volleyballshoes/app/icons/chart-histogram.png", false, new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleSidebarClick("statistic");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sidebar1 = new com.DuAn1.volleyballshoes.app.ui.component.Sidebar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidebar1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidebar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Xử lý chuyển trang bằng key
    private void handleSidebarClick(String key) {
        jPanel2.removeAll();
        jPanel2.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;
        switch (key) {
            case "home":
                jPanel2.add(new javax.swing.JLabel("Trang chủ", javax.swing.SwingConstants.CENTER), gbc);
                break;
            case "sell":
                jPanel2.add(new javax.swing.JLabel("Bán hàng", javax.swing.SwingConstants.CENTER), gbc);
                break;
            case "product":
                com.DuAn1.volleyballshoes.app.ui.ProductManagement pm = new com.DuAn1.volleyballshoes.app.ui.ProductManagement();
                pm.setPreferredSize(new java.awt.Dimension(1100, 650)); // Kích thước hợp lý
                jPanel2.add(pm, gbc);
                break;
            case "staff":
                StaffManagement sm = new StaffManagement();
                jPanel2.add(new javax.swing.JLabel("Nhân viên", javax.swing.SwingConstants.CENTER), gbc);
                jPanel2.add(sm);
                break;
            case "promotion":
                jPanel2.add(new javax.swing.JLabel("Khuyến mãi", javax.swing.SwingConstants.CENTER), gbc);
                break;
            case "invoice":
                jPanel2.add(new javax.swing.JLabel("Hóa đơn", javax.swing.SwingConstants.CENTER), gbc);
                break;
            case "customer":
                jPanel2.add(new javax.swing.JLabel("Khách hàng", javax.swing.SwingConstants.CENTER), gbc);
                break;
            case "statistic":
                jPanel2.add(new javax.swing.JLabel("Thống kê", javax.swing.SwingConstants.CENTER), gbc);
                break;
        }
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.DuAn1.volleyballshoes.app.ui.component.Sidebar sidebar1;
    // End of variables declaration//GEN-END:variables
}
